
version: '3.7'
services:
  mongodb_container:
    image: mongo:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  web:
    build: .
    ports:
      - 8000:8000
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      token_key: ${token_key}
      SECRET_KEY: ${SECRET_KEY}
      APP_SECRET: ${APP_SECRET}
    links: 
     - mongodb_container

volumes:
  mongodb_data_container: